// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAvQNgL2DNb7dT-7UjsJoeV8u8LJWcVhc',
    appId: '1:1090356891582:web:7521d3a88d53ed137d33ef',
    messagingSenderId: '1090356891582',
    projectId: 'lifting-progress-tracker',
    authDomain: 'lifting-progress-tracker.firebaseapp.com',
    storageBucket: 'lifting-progress-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Vrukn3HQl86tL-xJ1TpZQKt1PhRcwkc',
    appId: '1:1090356891582:android:d15ee93f29df10967d33ef',
    messagingSenderId: '1090356891582',
    projectId: 'lifting-progress-tracker',
    storageBucket: 'lifting-progress-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqRphZFkUahhLb84GDckRAslSQY2xw0tU',
    appId: '1:1090356891582:ios:7dfad7c0516d72b97d33ef',
    messagingSenderId: '1090356891582',
    projectId: 'lifting-progress-tracker',
    storageBucket: 'lifting-progress-tracker.appspot.com',
    iosClientId:
        '1090356891582-itlmdg551rp2ph041iq6smcsheppu1m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.liftingProgressTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqRphZFkUahhLb84GDckRAslSQY2xw0tU',
    appId: '1:1090356891582:ios:7dfad7c0516d72b97d33ef',
    messagingSenderId: '1090356891582',
    projectId: 'lifting-progress-tracker',
    storageBucket: 'lifting-progress-tracker.appspot.com',
    iosClientId:
        '1090356891582-itlmdg551rp2ph041iq6smcsheppu1m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.liftingProgressTracker',
  );
}
