const String homeRouteLabel = '/';
const String statisticsRouteLabel = 'Statistic';
const String calendarRouteLabel = "Calendar";
const String trainingplanListRouteLabel = "Training Schedules";
const String exerciseRouteLabel = "Exercise";
const String trainingDayRouteLabel = "Training Day";
const String trainingPeriodRouteLabel = "Training Period";
const String trainingPlanRouteLabel = "Training Schedule";
final List<String> tableHeaderLabels = ["Exercise", "Weight", "Repeats"];
